import "@/styles/globals.css";

import { Nunito } from "next/font/google";
import db from "@/server/db";
import { MaxWidthWrapper } from "@/components/MaxWidthWrapper";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // console.log(db);
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <main className="h-full">
          <MaxWidthWrapper>{children}</MaxWidthWrapper>
        </main>
      </body>
    </html>
  );
}
